[package]
name = "macros"
version = "0.1.0"
authors = ["BB20101997 <bb-github@t-online.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.25"
syn = "0.14.4"
quote = "1.0.9"
